# Generated by Django 5.0 on 2024-01-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friend_intra_pk_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
