# Generated by Django 5.0 on 2024-01-24 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_pk_id', models.CharField(max_length=100)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
